#!/bin/bash

# Create release directory
mkdir -p ./releases/3.x/android/br/com/uol/pagseguro/plugpag/3.6.1

# Add gradle package info to release folder
cp ./lib/plugpag/*{.pom,.aar} ./releases/3.x/android/br/com/uol/pagseguro/plugpag/3.6.1

# Rebuild aar files from modified sources
cd ./src/patched/ && zip -r -u -v ../../releases/3.x/android/br/com/uol/pagseguro/plugpag/3.6.1/plugpag-3.6.1.aar ./* && cd ../../
